on:
  workflow_dispatch:

jobs:
  check_resource_usage:
    permissions:
      id-token: write
      contents: read
    name: Check resource usage on Rocky server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          proxy: 192.168.4.77:3080
          version: auto

      - name: Export SSH config via tbot
        run: tbot start --oneshot -c ./action_support/server_bot.yaml

      - name: Install sysstat and run mpstat
        run: |
          ssh -F ./ssh_out/ssh_config tigerit@myinstance.192.168.4.77 \
          "command -v mpstat >/dev/null || sudo dnf install -y sysstat; mpstat 1 5"
